sources:
  - name: source
    database: "dbt-learning"
    freshness:
      warn_after: {count: 2, period: day}
      error_after: {count: 7, period: day}
    loaded_at_field: _synced_at

    tables:
        - name: fact_sales
        - name: fact_returns
        - name: dim_customer
        - name: dim_product
        - name: dim_store
        - name: dim_date

